---
- name: deploy vsftpd
  hosts: server2
  become: yes
  tasks: 
  - name: install vsftpd
    yum: name=vsftpd
  - name: enable vsftpd
    service:
      name: vsftpd
      enabled: yes
      state: started
  - name: create readme file
    copy:
      content: "something friendly 2nd time\n"
      dest: /var/ftp/pub/README
      force: yes 
      mode: 0444
...
